-- Oracle Database 10g: Administration Workshop I
-- Oracle Server Technologies - Curriculum Development
--
-- ***Training purposes only***
-- ***Not appropriate for production use***
--
prompt This script performs creates the DBA1 user (password: oracle)
prompt and grants appropriate privileges and roles for SYSDBA functions

CONNECT / as sysdba
spool lab_05_01.txt
CREATE USER "DBA1" PROFILE "DEFAULT" IDENTIFIED BY "oracle" DEFAULT TABLESPACE "SYSTEM" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT ADMINISTER ANY SQL TUNING SET TO "DBA1";
GRANT ADMINISTER DATABASE TRIGGER TO "DBA1";
EXEC dbms_resource_manager_privs.grant_system_privilege(privilege_name=>'ADMINISTER_RESOURCE_MANAGER', grantee_name=>'DBA1', admin_option=>FALSE);

GRANT ADMINISTER SQL TUNING SET TO "DBA1";
GRANT ADVISOR TO "DBA1";
GRANT ALTER ANY CLUSTER TO "DBA1";
GRANT ALTER ANY DIMENSION TO "DBA1";
GRANT ALTER ANY EVALUATION CONTEXT TO "DBA1" WITH ADMIN OPTION;
GRANT ALTER ANY INDEX TO "DBA1";
GRANT ALTER ANY INDEXTYPE TO "DBA1";
GRANT ALTER ANY LIBRARY TO "DBA1";
GRANT ALTER ANY MATERIALIZED VIEW TO "DBA1";
GRANT ALTER ANY OUTLINE TO "DBA1";
GRANT ALTER ANY PROCEDURE TO "DBA1";
GRANT ALTER ANY ROLE TO "DBA1";
GRANT ALTER ANY RULE TO "DBA1" WITH ADMIN OPTION;
GRANT ALTER ANY RULE SET TO "DBA1" WITH ADMIN OPTION;
GRANT ALTER ANY SEQUENCE TO "DBA1";
GRANT ALTER ANY SQL PROFILE TO "DBA1";
GRANT ALTER ANY TABLE TO "DBA1";
GRANT ALTER ANY TRIGGER TO "DBA1";
GRANT ALTER ANY TYPE TO "DBA1";
GRANT ALTER DATABASE TO "DBA1";
GRANT ALTER PROFILE TO "DBA1";
GRANT ALTER RESOURCE COST TO "DBA1";
GRANT ALTER ROLLBACK SEGMENT TO "DBA1";
GRANT ALTER SESSION TO "DBA1";
GRANT ALTER SYSTEM TO "DBA1";
GRANT ALTER TABLESPACE TO "DBA1";
GRANT ALTER USER TO "DBA1";
GRANT ANALYZE ANY TO "DBA1";
GRANT AUDIT ANY TO "DBA1";
GRANT AUDIT SYSTEM TO "DBA1";
GRANT BACKUP ANY TABLE TO "DBA1";
GRANT BECOME USER TO "DBA1";
GRANT CHANGE NOTIFICATION TO "DBA1";
GRANT COMMENT ANY TABLE TO "DBA1";
GRANT CREATE ANY CLUSTER TO "DBA1";
GRANT CREATE ANY CONTEXT TO "DBA1";
GRANT CREATE ANY DIMENSION TO "DBA1";
GRANT CREATE ANY DIRECTORY TO "DBA1";
GRANT CREATE ANY EVALUATION CONTEXT TO "DBA1" WITH ADMIN OPTION;
GRANT CREATE ANY INDEX TO "DBA1";
GRANT CREATE ANY INDEXTYPE TO "DBA1";
GRANT CREATE ANY JOB TO "DBA1";
GRANT CREATE ANY LIBRARY TO "DBA1";
GRANT CREATE ANY MATERIALIZED VIEW TO "DBA1";
GRANT CREATE ANY OPERATOR TO "DBA1";
GRANT CREATE ANY OUTLINE TO "DBA1";
GRANT CREATE ANY PROCEDURE TO "DBA1";
GRANT CREATE ANY RULE TO "DBA1" WITH ADMIN OPTION;
GRANT CREATE ANY RULE SET TO "DBA1" WITH ADMIN OPTION;
GRANT CREATE ANY SEQUENCE TO "DBA1";
GRANT CREATE ANY SQL PROFILE TO "DBA1";
GRANT CREATE ANY SYNONYM TO "DBA1";
GRANT CREATE ANY TABLE TO "DBA1";
GRANT CREATE ANY TRIGGER TO "DBA1";
GRANT CREATE ANY TYPE TO "DBA1";
GRANT CREATE ANY VIEW TO "DBA1";
GRANT CREATE CLUSTER TO "DBA1";
GRANT CREATE DATABASE LINK TO "DBA1";
GRANT CREATE DIMENSION TO "DBA1";
GRANT CREATE EVALUATION CONTEXT TO "DBA1" WITH ADMIN OPTION;
GRANT CREATE EXTERNAL JOB TO "DBA1";
GRANT CREATE INDEXTYPE TO "DBA1";
GRANT CREATE JOB TO "DBA1";
GRANT CREATE LIBRARY TO "DBA1";
GRANT CREATE MATERIALIZED VIEW TO "DBA1";
GRANT CREATE OPERATOR TO "DBA1";
GRANT CREATE PROCEDURE TO "DBA1";
GRANT CREATE PROFILE TO "DBA1";
GRANT CREATE PUBLIC DATABASE LINK TO "DBA1";
GRANT CREATE PUBLIC SYNONYM TO "DBA1";
GRANT CREATE ROLE TO "DBA1";
GRANT CREATE ROLLBACK SEGMENT TO "DBA1";
GRANT CREATE RULE TO "DBA1" WITH ADMIN OPTION;
GRANT CREATE RULE SET TO "DBA1" WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO "DBA1";
GRANT CREATE SESSION TO "DBA1";
GRANT CREATE SYNONYM TO "DBA1";
GRANT CREATE TABLE TO "DBA1";
GRANT CREATE TABLESPACE TO "DBA1";
GRANT CREATE TRIGGER TO "DBA1";
GRANT CREATE TYPE TO "DBA1";
GRANT CREATE USER TO "DBA1";
GRANT CREATE VIEW TO "DBA1";
GRANT DEBUG ANY PROCEDURE TO "DBA1";
GRANT DEBUG CONNECT SESSION TO "DBA1";
GRANT DELETE ANY TABLE TO "DBA1";
EXEC dbms_aqadm.grant_system_privilege(privilege=>'DEQUEUE_ANY', grantee=>'DBA1', admin_option=>TRUE);
COMMIT;

GRANT DROP ANY CLUSTER TO "DBA1";
GRANT DROP ANY CONTEXT TO "DBA1";
GRANT DROP ANY DIMENSION TO "DBA1";
GRANT DROP ANY DIRECTORY TO "DBA1";
GRANT DROP ANY EVALUATION CONTEXT TO "DBA1" WITH ADMIN OPTION;
GRANT DROP ANY INDEX TO "DBA1";
GRANT DROP ANY INDEXTYPE TO "DBA1";
GRANT DROP ANY LIBRARY TO "DBA1";
GRANT DROP ANY MATERIALIZED VIEW TO "DBA1";
GRANT DROP ANY OPERATOR TO "DBA1";
GRANT DROP ANY OUTLINE TO "DBA1";
GRANT DROP ANY PROCEDURE TO "DBA1";
GRANT DROP ANY ROLE TO "DBA1";
GRANT DROP ANY RULE TO "DBA1" WITH ADMIN OPTION;
GRANT DROP ANY RULE SET TO "DBA1" WITH ADMIN OPTION;
GRANT DROP ANY SEQUENCE TO "DBA1";
GRANT DROP ANY SQL PROFILE TO "DBA1";
GRANT DROP ANY SYNONYM TO "DBA1";
GRANT DROP ANY TABLE TO "DBA1";
GRANT DROP ANY TRIGGER TO "DBA1";
GRANT DROP ANY TYPE TO "DBA1";
GRANT DROP ANY VIEW TO "DBA1";
GRANT DROP PROFILE TO "DBA1";
GRANT DROP PUBLIC DATABASE LINK TO "DBA1";
GRANT DROP PUBLIC SYNONYM TO "DBA1";
GRANT DROP ROLLBACK SEGMENT TO "DBA1";
GRANT DROP TABLESPACE TO "DBA1";
GRANT DROP USER TO "DBA1";
EXEC dbms_aqadm.grant_system_privilege(privilege=>'ENQUEUE_ANY', grantee=>'DBA1', admin_option=>TRUE);
COMMIT;

GRANT EXECUTE ANY CLASS TO "DBA1";
GRANT EXECUTE ANY EVALUATION CONTEXT TO "DBA1" WITH ADMIN OPTION;
GRANT EXECUTE ANY INDEXTYPE TO "DBA1";
GRANT EXECUTE ANY LIBRARY TO "DBA1";
GRANT EXECUTE ANY OPERATOR TO "DBA1";
GRANT EXECUTE ANY PROCEDURE TO "DBA1";
GRANT EXECUTE ANY PROGRAM TO "DBA1";
GRANT EXECUTE ANY RULE TO "DBA1" WITH ADMIN OPTION;
GRANT EXECUTE ANY RULE SET TO "DBA1" WITH ADMIN OPTION;
GRANT EXECUTE ANY TYPE TO "DBA1";
GRANT EXPORT FULL DATABASE TO "DBA1";
GRANT FLASHBACK ANY TABLE TO "DBA1";
GRANT FORCE ANY TRANSACTION TO "DBA1";
GRANT FORCE TRANSACTION TO "DBA1";
GRANT GLOBAL QUERY REWRITE TO "DBA1";
GRANT GRANT ANY OBJECT PRIVILEGE TO "DBA1";
GRANT GRANT ANY PRIVILEGE TO "DBA1";
GRANT GRANT ANY ROLE TO "DBA1";
GRANT IMPORT FULL DATABASE TO "DBA1";
GRANT INSERT ANY TABLE TO "DBA1";
GRANT LOCK ANY TABLE TO "DBA1";
GRANT MANAGE ANY FILE GROUP TO "DBA1";
EXEC dbms_aqadm.grant_system_privilege(privilege=>'MANAGE_ANY', grantee=>'DBA1', admin_option=>TRUE);
COMMIT;

GRANT MANAGE FILE GROUP TO "DBA1";
GRANT MANAGE SCHEDULER TO "DBA1";
GRANT MANAGE TABLESPACE TO "DBA1";
GRANT MERGE ANY VIEW TO "DBA1";
GRANT ON COMMIT REFRESH TO "DBA1";
GRANT QUERY REWRITE TO "DBA1";
GRANT READ ANY FILE GROUP TO "DBA1";
GRANT RESTRICTED SESSION TO "DBA1";
GRANT RESUMABLE TO "DBA1";
GRANT SELECT ANY SEQUENCE TO "DBA1";
GRANT SELECT ANY TABLE TO "DBA1" WITH ADMIN OPTION;
GRANT SELECT ANY TRANSACTION TO "DBA1";
GRANT SYSDBA TO "DBA1" WITH ADMIN OPTION;
GRANT SYSOPER TO "DBA1" WITH ADMIN OPTION;
GRANT UNDER ANY TABLE TO "DBA1";
GRANT UNDER ANY TYPE TO "DBA1";
GRANT UNDER ANY VIEW TO "DBA1";
GRANT UNLIMITED TABLESPACE TO "DBA1";
GRANT UPDATE ANY TABLE TO "DBA1";
GRANT SELECT ON "SYSTEM"."DEF$_AQCALL" TO "DBA1" WITH GRANT OPTION;
GRANT SELECT ON "SYSTEM"."DEF$_CALLDEST" TO "DBA1" WITH GRANT OPTION;
GRANT SELECT ON "SYSTEM"."DEF$_DESTINATION" TO "DBA1" WITH GRANT OPTION;
GRANT SELECT ON "SYSTEM"."DEF$_ERROR" TO "DBA1" WITH GRANT OPTION;
GRANT SELECT ON "SYSTEM"."DEF$_LOB" TO "DBA1" WITH GRANT OPTION;
GRANT DELETE ON "SYSTEM"."DEF$_TEMP$LOB" TO "DBA1" WITH GRANT OPTION;
GRANT INSERT ON "SYSTEM"."DEF$_TEMP$LOB" TO "DBA1" WITH GRANT OPTION;
GRANT SELECT ON "SYSTEM"."DEF$_TEMP$LOB" TO "DBA1" WITH GRANT OPTION;
GRANT UPDATE ON "SYSTEM"."DEF$_TEMP$LOB" TO "DBA1" WITH GRANT OPTION;
GRANT SELECT ON "SYSTEM"."MVIEW_EVALUATIONS" TO "DBA1" WITH GRANT OPTION;
GRANT SELECT ON "SYSTEM"."MVIEW_EXCEPTIONS" TO "DBA1" WITH GRANT OPTION;
GRANT SELECT ON "SYSTEM"."MVIEW_FILTER" TO "DBA1" WITH GRANT OPTION;
GRANT SELECT ON "SYSTEM"."MVIEW_FILTERINSTANCE" TO "DBA1" WITH GRANT OPTION;
GRANT SELECT ON "SYSTEM"."MVIEW_LOG" TO "DBA1" WITH GRANT OPTION;
GRANT SELECT ON "SYSTEM"."MVIEW_RECOMMENDATIONS" TO "DBA1" WITH GRANT OPTION;
GRANT SELECT ON "SYSTEM"."MVIEW_WORKLOAD" TO "DBA1" WITH GRANT OPTION;
GRANT SELECT ON "SYSTEM"."REPCAT$_REPPROP" TO "DBA1" WITH GRANT OPTION;
GRANT SELECT ON "SYSTEM"."REPCAT$_REPSCHEMA" TO "DBA1" WITH GRANT OPTION;
GRANT SELECT ON "WMSYS"."WM$ANC_VERSION_VIEW" TO "DBA1";
GRANT SELECT ON "WMSYS"."WM$RIC_LOCKING_TABLE" TO "DBA1";
GRANT "AQ_ADMINISTRATOR_ROLE" TO "DBA1" WITH ADMIN OPTION;
GRANT "AQ_USER_ROLE" TO "DBA1" WITH ADMIN OPTION;
GRANT "AUTHENTICATEDUSER" TO "DBA1" WITH ADMIN OPTION;
GRANT "CONNECT" TO "DBA1" WITH ADMIN OPTION;
GRANT "CTXAPP" TO "DBA1" WITH ADMIN OPTION;
GRANT "DBA" TO "DBA1" WITH ADMIN OPTION;
GRANT "DELETE_CATALOG_ROLE" TO "DBA1" WITH ADMIN OPTION;
GRANT "EJBCLIENT" TO "DBA1" WITH ADMIN OPTION;
GRANT "EXECUTE_CATALOG_ROLE" TO "DBA1" WITH ADMIN OPTION;
GRANT "EXP_FULL_DATABASE" TO "DBA1" WITH ADMIN OPTION;
GRANT "GATHER_SYSTEM_STATISTICS" TO "DBA1" WITH ADMIN OPTION;
GRANT "HS_ADMIN_ROLE" TO "DBA1" WITH ADMIN OPTION;
GRANT "IMP_FULL_DATABASE" TO "DBA1" WITH ADMIN OPTION;
GRANT "JAVADEBUGPRIV" TO "DBA1" WITH ADMIN OPTION;
GRANT "JAVAIDPRIV" TO "DBA1" WITH ADMIN OPTION;
GRANT "JAVASYSPRIV" TO "DBA1" WITH ADMIN OPTION;
GRANT "JAVAUSERPRIV" TO "DBA1" WITH ADMIN OPTION;
GRANT "JAVA_ADMIN" TO "DBA1" WITH ADMIN OPTION;
GRANT "JAVA_DEPLOY" TO "DBA1" WITH ADMIN OPTION;
GRANT "LOGSTDBY_ADMINISTRATOR" TO "DBA1" WITH ADMIN OPTION;
GRANT "MGMT_USER" TO "DBA1" WITH ADMIN OPTION;
GRANT "OEM_MONITOR" TO "DBA1" WITH ADMIN OPTION;
GRANT "OLAP_DBA" TO "DBA1" WITH ADMIN OPTION;
GRANT "OLAP_USER" TO "DBA1" WITH ADMIN OPTION;
GRANT "RECOVERY_CATALOG_OWNER" TO "DBA1" WITH ADMIN OPTION;
GRANT "RESOURCE" TO "DBA1" WITH ADMIN OPTION;
GRANT "SCHEDULER_ADMIN" TO "DBA1" WITH ADMIN OPTION;
GRANT "SELECT_CATALOG_ROLE" TO "DBA1" WITH ADMIN OPTION;
GRANT "XDBADMIN" TO "DBA1" WITH ADMIN OPTION;
GRANT "XDBWEBSERVICES" TO "DBA1" WITH ADMIN OPTION;

prompt
prompt Lab_05_01 completed. You may now login as:
prompt   dba1/oracle
prompt
spool off
exit

